// General Linux-like sources
#include "wl_monitor.c"
#include "wl_window.c"
#include "wl_init.c"

// Note: These sources are generated by wayland-scanner, and distributed in sdk-linux-*
// See e.g. https://github.com/hexops/sdk-linux-x86_64/blob/main/generate-wayland.sh 
#include "wayland-viewporter-client-protocol.c"
#include "wayland-xdg-decoration-client-protocol.c"
#include "wayland-xdg-shell-client-protocol.c"
#include "wayland-idle-inhibit-unstable-v1-client-protocol.c"
#include "wayland-pointer-constraints-unstable-v1-client-protocol.c"
#include "wayland-relative-pointer-unstable-v1-client-protocol.c"