#include "out/Debug/gen/src/dawn_native/ChainUtils_autogen.cpp"
#include "out/Debug/gen/src/dawn_native/ProcTable.cpp"
#include "out/Debug/gen/src/dawn_native/wgpu_structs_autogen.cpp"
#include "out/Debug/gen/src/dawn_native/ValidationUtils_autogen.cpp"
#include "out/Debug/gen/src/dawn_native/webgpu_absl_format_autogen.cpp"
#include "out/Debug/gen/src/dawn_native/ObjectType_autogen.cpp"
